/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asistensi;

import javax.swing.JTextField;


/**
 *
 * @author Laptop
 */
public class TUGAS2 extends javax.swing.JFrame {

    /**
     * Creates new form TUGAS2
     */
    public TUGAS2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hitung2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        inputa = new javax.swing.JLabel();
        inputn = new javax.swing.JLabel();
        inputx = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        x = new javax.swing.JTextField();
        pilihsoal = new javax.swing.JComboBox();
        penyelesaian = new javax.swing.JTextField();
        tampilansoal = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        hitung2.setText("HITUNG");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));

        inputa.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        inputa.setText("Masukkan nilai a =");

        inputn.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        inputn.setText("Masukkan nilai n =");

        inputx.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        inputx.setText("Masukkan nilai x =");

        a.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });

        x.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        pilihsoal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pilihsoal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih soal", "Soal 2", "Soal 3", "Soal 4" }));
        pilihsoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihsoalActionPerformed(evt);
            }
        });

        penyelesaian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        penyelesaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penyelesaianActionPerformed(evt);
            }
        });

        tampilansoal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        hitung.setBackground(new java.awt.Color(255, 51, 51));
        hitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 102, 0));
        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keluar.setBackground(new java.awt.Color(255, 204, 0));
        keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        keluar.setForeground(new java.awt.Color(153, 0, 0));
        keluar.setText("X");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("HASIL PERHITUNGAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("APROKSIMASI f(x)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pilihsoal, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tampilansoal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputx, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(penyelesaian)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(keluar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(pilihsoal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tampilansoal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(keluar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputx, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(penyelesaian, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static double faktorial(int angka){
        int faktor = 1;
        for(int i = 1; i <= angka; i++){
        faktor = faktor * i;
        }
        return faktor;
}
    
    private void pilihsoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihsoalActionPerformed
        // TODO add your handling code here:
        switch(pilihsoal.getSelectedIndex()){
            case 1:
                a.setText(null);
                n.setText(null);
                x.setText(null);
                penyelesaian.setText(null);
                tampilansoal.setText("f(x) = sin(2x)");
                break;
            case 2:
                a.setText(null);
                n.setText(null);
                x.setText(null);
                penyelesaian.setText(null);
                tampilansoal.setText("f(x) = cosh(-6x)");
                break;
            case 3:
                a.setText(null);
                n.setText(null);
                x.setText(null);
                penyelesaian.setText(null);
                tampilansoal.setText("f(x) = ln(-x)");
                break;
            default:
                a.setText(null);
                n.setText(null);
                x.setText(null);
                penyelesaian.setText(null);
                tampilansoal.setText(null);
        }
    
    }//GEN-LAST:event_pilihsoalActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double a1 = Double.parseDouble(a.getText());
        double n1 = Double.parseDouble(n.getText());
        double x1 = Double.parseDouble(x.getText());
        double es = 0.5*Math.pow(10, (2-n1));
        double[] f = new double[1001];
        double error = 0;
        
        switch(pilihsoal.getSelectedIndex()){
            case 1:
                f[0] = Math.sin(Math.toRadians(2*a1))+ Math.cos(Math.toRadians(2*a1))*(Math.toRadians(x1-a1));
                for(int k=1; k<=1000; k++){
                    f[k] = f[k-1] + ((Math.pow(-1,k) * Math.sin(Math.toRadians(2*a1)) * Math.pow(Math.toRadians(x1-a1), 2*k))/faktorial(2*k))
                            + ((Math.pow(-1,k) * Math.pow(2, 2*k+1) * Math.cos(Math.toRadians(2*a1)) * Math.pow(Math.toRadians(x1-a1),2*k+1))/faktorial(2*k+1));
                    double ea = ((f[k] - f[k-1])/f[k])*100;
                    if(Math.abs(ea) < es){
                        error += f[k];
                break;
                    }
                }
                double jawab1 = Math.floor(error*1000)/1000;
                penyelesaian.setText(String.valueOf(jawab1));
                break;
                        
            case 2:           
                f[0] = (Math.exp(6*a1)+Math.exp(-6*a1))/2;
                for(int k=1; k<=1000; k++){
                    
                if(a1==0){
                    f[k] = f[k-1] + Math.pow(6*x1,2*k)/faktorial(2*k);
                }else{
                    f[k] = f[k-1] + ((Math.exp(6*a1) + Math.pow(-1,k) * Math.exp(-6*a1))*(Math.pow(6,k)*Math.pow(x1-a1, k)))/(2*(faktorial(k)));
                }
                double ea = ((f[k] - f[k-1])/f[k])*100;
                if(Math.abs(ea)<es){
                error += f[k];
                break;
                }
            }
                double jawab2 = Math.floor(error*1000)/1000;
                penyelesaian.setText(String.valueOf(jawab2));
                break;
                
            case 3:
               f[0] = Math.log(-a1);
                for(int k=1; k<=1000; k++){
                    f[k] = f[k-1] + (Math.pow(-1, k+1) * Math.pow(x1-a1, k))/(k*Math.pow(a1,k));
                    double ea = ((f[k] - f[k-1])/f[k])*100;
                    if(Math.abs(ea) < es){
                        error += f[k];
                        break;
                    }
                }
                double jawab3 = Math.floor(error*1000)/1000;
                penyelesaian.setText(String.valueOf(jawab3));
                break;
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void penyelesaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penyelesaianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penyelesaianActionPerformed

    
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        a.setText(null);
        n.setText(null);
        x.setText(null);
        penyelesaian.setText(null);
        tampilansoal.setText(null);
    }//GEN-LAST:event_resetActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed
                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TUGAS2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton hitung;
    private javax.swing.JButton hitung2;
    private javax.swing.JLabel inputa;
    private javax.swing.JLabel inputn;
    private javax.swing.JLabel inputx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField n;
    private javax.swing.JTextField penyelesaian;
    private javax.swing.JComboBox pilihsoal;
    private javax.swing.JButton reset;
    private javax.swing.JTextField tampilansoal;
    private javax.swing.JTextField x;
    // End of variables declaration//GEN-END:variables

    private Object jawaban1(JTextField a, JTextField n, JTextField x) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private Object jawaban2(JTextField a, JTextField n, JTextField x) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String jawaban3(JTextField a, JTextField x, JTextField n) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
